name: scp files to hostinger
on: [push]
jobs:

  deploy-control:
    name: Control
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: copy file via ssh key
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USER }}
        password: ${{ secrets.HOSTINGER_PASSWORD}}
        port: 65002
        source: "."
        target: /home/u331460685/domains/app.idsy.com.br/

  deploy-registroartistico:
      name: RegistroArtistico
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          password: ${{ secrets.HOSTINGER_PASSWORD}}
          port: 65002
          source: "public_html/view/registroartistico/*"
          target: "/home/u331460685/domains/app.registroartistico.com.br/public_html/"
          overwrite: true
          strip_components: 3   # <-- remove os 3 nÃ­veis do path (public_html/view/registroartistico)
          debug: true
